/**
 * Author: rodrigo
 * 2015
 */
#pragma once

#include <vector>
#include "Vertex.h"
#include <ostream>

using namespace std;

class Triangle
{
public:
	// Constructor
	Triangle(const Vertex *_vertex1, const Vertex *_vertex2, const Vertex *_vertex3);
	// Destructor
	~Triangle();

	friend std::ostream &operator<<(std::ostream &_stream, const Triangle &_triangle);

	// Returns the desired neighbor
	inline Triangle * getNeighbor(const int index) const
	{
		return neighbors[index % 3];
	}

	// Returns the desired vertex
	inline Vertex * getVertex(const int index) const
	{
		return vertices[index % 3];
	}

	// Checks if the given vertex is inside the current triangle
	bool contains(const Vertex *_vertex) const;
	// Returns the triangles generated by splitting the current triangle using the given vertex
	vector<Triangle> split(const Vertex &_vertex) const;
	// Sets the neighbors of the current triangle
	void setNeighbors(const Triangle *_t1, const Triangle *_t2, const Triangle *_t3);

private:
	vector<Vertex *> vertices;
	vector<Triangle *> neighbors;

	// Adds the vertices in CCW
	void addInCCW(const Vertex *_vertex1, const Vertex *_vertex2, const Vertex *_vertex3);
};
